version = 1

test_patterns = ["**/*_test.go"]
exclude_patterns = [
  "pkg/client/**",
  "vendor/**",
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/vagababov/serving"]
  dependencies_vendored = true
